name: Scheduled Publish

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
